[phases.setup]
# instala python + pip pelo Nix (sem ensurepip)
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/python -m pip install --upgrade pip setuptools wheel",
  "/opt/venv/bin/python -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
